name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# test the build on ubuntu-latest
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest

          